- name: Install binutils
  package:
    name:
      - python3-dev
      - python3-venv
      - binutils
    state: present
  when: ansible_os_family in ['Debian']

- name: Install binutils
  package:
    name:
      - python3-devel
      - binutils
    state: present
  when: ansible_os_family in ['RedHat', 'Rocky']

- name: Create venv
  command: python3 -m venv .venv

- name: Debian 10
  shell: |
    apt install build-essential
    .venv/bin/pip install --upgrade pip 
    .venv/bin/pip install pyqt6==6.5 pyinstaller
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '10'

- name: Install in venv
  command: .venv/bin/pip install pyqt6 pyinstaller
  when: not (ansible_os_family == 'Debian' and ansible_lsb.release == '10')
  
- name: Create pkg
  command: .venv/bin/pyinstaller ../qstore.py
