- name: Install binutils
  package:
    name:
      - python3-dev
      - python3-venv
      - binutils
    state: present

- name: Create venv
  shell: |
    python3 -m venv .venv
    source .venv/bin/activate
    pip install pyqt6 pyinstaller 
  
- name: Create pkg
  command: .venv/bin/pyinstaller qstore.py
