- name: Install binutils
  package:
    name:
      - python3-dev
      - python3-venv 
      - binutils
    state: present

- name: Create venv
  pip:
    name:
      - pyqt6 
      - pyinstaller 
    state: present
    virtualenv: .venv
    virtualenv_python: python3

- name: Create pkg
  command: .venv/bin/pyinstaller qstore.py
