- name: Install binutils
  package:
    name:
      - python3-dev 
      - binutils
    state: present

- name: Create venv
  pip:
    executable: bin/pip
    name:
      - pyqt6 
      - pyinstaller 
    state: present
    virtualenv: .venv
    virtualenv_command: python3 -m venv

- name: Create pkg
  command: .venv/bin/pyinstaller qstore.py
