- name: Install binutils
  package:
    name:
      - python3-dev
      - python3-venv
      - binutils
    state: present

- name: Create venv
  command: python3 -m venv .venv

- name: Install in venv
  command: .venv/bin/pip install pyqt6 pyinstaller 
  
- name: Create pkg
  command: .venv/bin/pyinstaller ../qstore.py
