name: debian-10

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    container: debian:10
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt -y install ansible
