name: debian-12

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    container: debian:12
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: apt -y install ansible
