name: rocky-9

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:9
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - run: dnf -y install ansible
